#!/usr/bin/env node
/**
 * Generates the bundled font-face manifests from the installed @fontsource packages:
 *
 *   src/fonts/generated/faces.ts    latin faces (every normal weight + italics) — eager, tiny
 *   src/fonts/generated/facesJp.ts  Japanese families (one weight, unicode-range chunks) — lazy chunk
 *
 * Only .woff2 files are referenced (Chromium/Electron always supports woff2), so the build does
 * not ship the .woff fallbacks @fontsource's CSS would pull in. Each file is referenced with a
 * literal `new URL('…', import.meta.url)` so Vite emits it as an asset, and nothing downloads until
 * a face is actually used (FontFace objects start "unloaded").
 *
 * Run from the repo root:  node src/fonts/tools/gen-faces.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '../../..');
const fsDir = path.join(root, 'node_modules/@fontsource');
const outDir = path.join(here, '../generated');

/** Japanese families: package → the single weight we bundle (full japanese + latin chunks). */
const JAPANESE = {
  'noto-sans-jp': 700,
  'noto-serif-jp': 700,
  'shippori-mincho': 500,
  'zen-antique': 400,
  'yuji-syuku': 400,
  'dela-gothic-one': 400,
  'rampart-one': 400,
  'reggae-one': 400,
};

const LATIN_RANGE =
  'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD';

const rel = (pkg, file) => `../../../node_modules/@fontsource/${pkg}/files/${file}`;
const q = (s) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

function parseCss(file) {
  const css = fs.readFileSync(file, 'utf8');
  const out = [];
  const re = /\/\* ([^*]+) \*\/\s*@font-face \{([^}]*)\}/g;
  let m;
  while ((m = re.exec(css))) {
    const body = m[2];
    out.push({
      name: m[1].trim(),
      family: (body.match(/font-family: '([^']+)'/) || [])[1],
      weight: Number((body.match(/font-weight: (\d+)/) || [])[1]),
      style: (body.match(/font-style: (\w+)/) || [])[1],
      woff2: (body.match(/url\(\.\/files\/([^)]+\.woff2)\)/) || [])[1],
      range: (body.match(/unicode-range: ([^;]+);/) || [])[1] ?? null,
    });
  }
  return out;
}

const families = [];
const latinFaces = [];
const jpFaces = [];
const ranges = [];
const rangeIndex = (r) => {
  let i = ranges.indexOf(r);
  if (i < 0) {
    ranges.push(r);
    i = ranges.length - 1;
  }
  return i;
};

for (const pkg of fs.readdirSync(fsDir).sort()) {
  const metaPath = path.join(fsDir, pkg, 'metadata.json');
  if (!fs.existsSync(metaPath)) continue;
  const meta = JSON.parse(fs.readFileSync(metaPath, 'utf8'));
  const files = new Set(fs.readdirSync(path.join(fsDir, pkg, 'files')));

  if (JAPANESE[pkg]) {
    const w = JAPANESE[pkg];
    const faces = parseCss(path.join(fsDir, pkg, `${w}.css`)).filter(
      (f) => /-\[\d+\]-/.test(f.name) || f.name.endsWith(`-latin-${w}-normal`),
    );
    for (const f of faces) {
      if (!f.woff2 || !files.has(f.woff2)) throw new Error(`missing ${pkg}/${f.woff2}`);
      jpFaces.push({ family: f.family, weight: w, range: rangeIndex(f.range ?? LATIN_RANGE), url: rel(pkg, f.woff2) });
    }
    families.push({ pkg, family: faces[0].family, weights: [w], italic: false, jp: true });
    continue;
  }

  const weights = [];
  let italic = false;
  for (const w of meta.weights) {
    for (const style of ['normal', 'italic']) {
      if (!meta.styles.includes(style)) continue;
      const file = `${pkg}-latin-${w}-${style}.woff2`;
      if (!files.has(file)) continue;
      // Family name exactly as declared by the package CSS.
      const css = path.join(fsDir, pkg, `latin-${w}${style === 'italic' ? '-italic' : ''}.css`);
      const fam = parseCss(css)[0]?.family ?? meta.family;
      latinFaces.push({ family: fam, weight: w, style, url: rel(pkg, file) });
      if (style === 'normal') weights.push(w);
      else italic = true;
    }
  }
  if (!weights.length) continue;
  families.push({ pkg, family: meta.family, weights, italic, jp: false });
}

const header = (what) =>
  `/* AUTO-GENERATED by src/fonts/tools/gen-faces.mjs — do not edit by hand. ${what} */\n/* eslint-disable */\n`;

let latin = header('Latin faces of the bundled @fontsource families.');
latin += `import type { BundledFamily } from '../types';\n\n`;
latin += `export const LATIN_RANGE = ${q(LATIN_RANGE)};\n\n`;
latin += `export const BUNDLED_FAMILIES: BundledFamily[] = [\n`;
for (const f of families)
  latin += `  { pkg: ${q(f.pkg)}, family: ${q(f.family)}, weights: [${f.weights.join(', ')}], italic: ${f.italic}, japanese: ${f.jp} },\n`;
latin += `];\n\n`;
latin += `/** [family, weight, italic (0|1), url] */\nexport const LATIN_FACES: [string, number, 0 | 1, string][] = [\n`;
for (const f of latinFaces)
  latin += `  [${q(f.family)}, ${f.weight}, ${f.style === 'italic' ? 1 : 0}, new URL(${q(f.url)}, import.meta.url).href],\n`;
latin += `];\n`;

let jp = header('Japanese families: unicode-range chunks (loaded lazily as a separate chunk).');
jp += `\n/** Shared unicode-range slices (identical across the Google Fonts JP families). */\n`;
jp += `export const JP_RANGES: string[] = [\n${ranges.map((r) => `  ${q(r)},`).join('\n')}\n];\n\n`;
jp += `/** [family, weight, range index, url] */\nexport const JP_FACES: [string, number, number, string][] = [\n`;
for (const f of jpFaces) jp += `  [${q(f.family)}, ${f.weight}, ${f.range}, new URL(${q(f.url)}, import.meta.url).href],\n`;
jp += `];\n`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'faces.ts'), latin);
fs.writeFileSync(path.join(outDir, 'facesJp.ts'), jp);

const size = (list) =>
  list.reduce((s, f) => s + fs.statSync(path.join(here, '../generated', f.url)).size, 0);
console.log(
  `families: ${families.length} · latin faces: ${latinFaces.length} (${(size(latinFaces) / 1e6).toFixed(2)} MB) · ` +
    `jp faces: ${jpFaces.length} (${(size(jpFaces) / 1e6).toFixed(2)} MB) · ranges: ${ranges.length}`,
);
