/**
 * WebAssembly runtime for the hot blur / box / median loops (kernels generated by
 * scripts/gen-wasm.mjs into blurWasm.generated.ts — see that script for what each kernel mirrors).
 *
 * - Loaded synchronously the first time a kernel is needed (the module is small and Chromium
 *   compiles it on the main thread in a few ms); if the synchronous constructor is refused
 *   (engines that limit sync compilation by size) it is compiled asynchronously and callers use
 *   the JavaScript path until it is ready.
 * - Whenever WebAssembly is missing or refused (CSP without 'wasm-unsafe-eval', old engine,
 *   instantiation error) `wasm()` returns null and every caller runs its existing JavaScript
 *   code, which produces bit-identical results.
 * - Memory: one linear memory used as a stack (`wasmMark` / `wasmAlloc` / `wasmRelease`), grown on
 *   demand and reused. A 4K (3840×2160) image needs from a few MB up to ~350 MB depending on the
 *   filter: bloom with radius ≤ 4 is the largest (~349 MB: full-size float grids at all three scales),
 *   the small-σ gaussian (σ < 1: watercolor, poster edges, …) ~285 MB, most others ≤ 64 MB. The stack
 *   never passes MAX_BYTES (1 GiB); an operation that would is run in JavaScript. Growing detaches
 *   every typed-array view of the old buffer, so callers keep byte addresses and take fresh views
 *   with `wasmHeap()` after their last allocation. Once no operation has needed more than 192 MB
 *   for 2 s, the instance is recreated so the memory is returned (a burst of big operations — a
 *   live preview on a 4K document — keeps reusing it).
 */
import { BLUR_WASM_BASE64 } from './blurWasm.generated';

type I = number;
type F = number;
/** Exports of the generated module (addresses are byte offsets into `memory`). */
export interface BlurWasm {
  memory: WebAssembly.Memory;
  hrow1(src: I, dst: I, w: I, stride: I, r: I, inv: F, alpha: F): void;
  hrow2(src: I, dst: I, w: I, stride: I, r: I, inv: F, alpha: F): void;
  hrow3(src: I, dst: I, w: I, stride: I, r: I, inv: F, alpha: F): void;
  hrow4(src: I, dst: I, w: I, stride: I, r: I, inv: F, alpha: F): void;
  hrow1x2(src: I, dst: I, src2: I, dst2: I, w: I, stride: I, r: I, inv: F, alpha: F): void;
  hrow2x2(src: I, dst: I, src2: I, dst2: I, w: I, stride: I, r: I, inv: F, alpha: F): void;
  hrow3x2(src: I, dst: I, src2: I, dst2: I, w: I, stride: I, r: I, inv: F, alpha: F): void;
  hrow4x2(src: I, dst: I, src2: I, dst2: I, w: I, stride: I, r: I, inv: F, alpha: F): void;
  vrow(S: I, add: I, rem: I, dst: I, n: I, inv: F): void;
  vrowext(S: I, add: I, rem: I, up: I, dst: I, n: I, inv: F, alpha: F): void;
  addrow(S: I, row: I, n: I): void;
  premul_row(bytes: I, f: I, n: I): void;
  unpremul_row(f: I, bytes: I, n: I): void;
  rgb_in(bytes: I, f: I, w: I): void;
  rgb_out(f: I, bytes: I, w: I): void;
  ds_premul_row(bytes: I, w: I, f: I, w2: I, cells: I): void;
  ds_norm(cells: I, w: I, f: I, w2: I, kh: I): void;
  us_unpremul_row(r0: I, r1: I, ty: F, xi0: I, xi1: I, xt: I, bytes: I, w: I): void;
  bb_h(src: I, dst: I, w: I, h: I, r: I, iarr: F): void;
  bb_v(src: I, dst: I, w: I, h: I, r: I, iarr: F, acc: I): void;
  bc_h(src: I, dst: I, w: I, h: I, r: I, iarr: F): void;
  bc_v(src: I, dst: I, w: I, h: I, r: I, iarr: F, acc: I): void;
  gs_h3_1(src: I, dst: I, w: I, h: I, k0: F, k1: F, k2: F): void;
  gs_h5_1(src: I, dst: I, w: I, h: I, k0: F, k1: F, k2: F, k3: F, k4: F): void;
  gs_h7_1(src: I, dst: I, w: I, h: I, k0: F, k1: F, k2: F, k3: F, k4: F, k5: F, k6: F): void;
  gs_h3_4(src: I, dst: I, w: I, h: I, k0: F, k1: F, k2: F): void;
  gs_h5_4(src: I, dst: I, w: I, h: I, k0: F, k1: F, k2: F, k3: F, k4: F): void;
  gs_h7_4(src: I, dst: I, w: I, h: I, k0: F, k1: F, k2: F, k3: F, k4: F, k5: F, k6: F): void;
  gs_v3(src: I, dst: I, n: I, h: I, k0: F, k1: F, k2: F): void;
  gs_v5(src: I, dst: I, n: I, h: I, k0: F, k1: F, k2: F, k3: F, k4: F): void;
  gs_v7(src: I, dst: I, n: I, h: I, k0: F, k1: F, k2: F, k3: F, k4: F, k5: F, k6: F): void;
  bloom_ds(
    d: I, w: I, h: I, lo: F, hi: F,
    cx0: I, cx1: I, cx2: I, f0: I, f1: I, f2: I, rb0: I, rb1: I, rb2: I,
    g0: I, g1: I, g2: I, ps0: I, ps1: I, ps2: I, inv255: I,
  ): void;
  bloom_lerp(p0: I, p1: I, xi: I, xi1: I, xt: I, T: I, D: I, w: I): void;
  bloom_row(
    d: I, w: I, w0: F, w1: F, w2: F, desat: I, sat: F, k: F, spill: I, inv255: I,
    m0: I, ty0: F, td0: I, pr0: I, pg0: I, pb0: I,
    m1: I, ty1: F, td1: I, pr1: I, pg1: I, pb1: I,
    m2: I, ty2: F, td2: I, pr2: I, pg2: I, pb2: I,
  ): void;
  med_rows3(src: I, dst: I, from: I, to: I): void;
  med_rows5(src: I, dst: I, from: I, to: I): void;
  med_rows7(src: I, dst: I, from: I, to: I): void;
  med_cols3(dst: I, w: I, r0: I, r1: I, r2: I): void;
  med_cols5(dst: I, w: I, r0: I, r1: I, r2: I, r3: I, r4: I): void;
  med_cols7(dst: I, w: I, r0: I, r1: I, r2: I, r3: I, r4: I, r5: I, r6: I): void;
}

export type BlurBackend = 'wasm' | 'js';
/**
 * 'auto' (or 'wasm') = WebAssembly when it can be loaded, else JavaScript; 'js' forces the
 * JavaScript loops (tests, benchmarks).
 */
export type BlurBackendSetting = 'auto' | 'wasm' | 'js';

/** First usable address (0 stays a "no allocation" marker). */
const BASE = 64;
/** Never let the stack pass 1 GiB (addresses stay positive int32 in every kernel and view index). */
const MAX_BYTES = 1 << 30;
/** Memory above this is handed back (instance recreated) once no operation has used it for shrinkDelayMs. */
let shrinkBytes = 192 << 20;
/**
 * Idle time before oversized memory is handed back: a burst of big operations (a filter's live
 * preview on a 4K document, a slider drag) keeps reusing the grown memory instead of growing it
 * again — page faults and zeroing — on every run.
 */
let shrinkDelayMs = 2000;
let shrinkTimer: ReturnType<typeof setTimeout> | null = null;
/** Highest stack position of the current outermost operation. */
let peak = BASE;

let state: 'idle' | 'loading' | 'ready' | 'failed' = 'idle';
let reason = '';
let mod: WebAssembly.Module | null = null;
let X: BlurWasm | null = null;
let setting: BlurBackendSetting = 'auto';
let top = BASE;
let heapCache: { buffer: ArrayBuffer; u8: Uint8Array; f32: Float32Array; f64: Float64Array; i32: Int32Array } | null = null;

/** Base64 → bytes without atob/Buffer (works in every engine). */
function decodeBase64(s: string): Uint8Array {
  const T = new Uint8Array(128);
  const A = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  for (let i = 0; i < A.length; i++) T[A.charCodeAt(i)] = i;
  let n = s.length;
  while (n > 0 && s[n - 1] === '=') n--;
  const out = new Uint8Array((n * 3) >> 2);
  let o = 0;
  for (let i = 0; i < n; i += 4) {
    const a = T[s.charCodeAt(i)],
      b = T[s.charCodeAt(i + 1)],
      c = i + 2 < n ? T[s.charCodeAt(i + 2)] : 0,
      d = i + 3 < n ? T[s.charCodeAt(i + 3)] : 0;
    const v = (a << 18) | (b << 12) | (c << 6) | d;
    out[o++] = v >> 16;
    if (o < out.length) out[o++] = (v >> 8) & 255;
    if (o < out.length) out[o++] = v & 255;
  }
  return out;
}

function instantiate(m: WebAssembly.Module) {
  X = new WebAssembly.Instance(m, {}).exports as unknown as BlurWasm;
  heapCache = null;
  top = BASE;
  peak = BASE;
}

function load() {
  if (state !== 'idle') return;
  if (typeof WebAssembly !== 'object' || typeof WebAssembly.Module !== 'function') {
    state = 'failed';
    reason = 'WebAssembly unavailable';
    return;
  }
  let bytes: Uint8Array;
  try {
    bytes = decodeBase64(BLUR_WASM_BASE64);
    mod = new WebAssembly.Module(bytes as BufferSource);
    instantiate(mod);
    state = 'ready';
  } catch (e) {
    X = null;
    mod = null;
    // A RangeError means the engine refuses synchronous compilation of this size: compile in the
    // background and keep using JavaScript until then. Anything else (CSP, unsupported features)
    // is final.
    if (e instanceof RangeError && typeof WebAssembly.compile === 'function') {
      state = 'loading';
      reason = 'compiling asynchronously';
      WebAssembly.compile(decodeBase64(BLUR_WASM_BASE64) as BufferSource)
        .then((m) => {
          mod = m;
          instantiate(m);
          state = 'ready';
          reason = '';
        })
        .catch((err) => {
          state = 'failed';
          reason = String(err);
        });
    } else {
      state = 'failed';
      reason = String(e);
    }
  }
}

/** The kernels, or null when the JavaScript path must be used. */
export function wasm(): BlurWasm | null {
  if (setting === 'js') return null;
  if (state === 'idle') load();
  return state === 'ready' ? X : null;
}

/** Which implementation the blur helpers currently use. */
export function blurBackend(): BlurBackend {
  return wasm() ? 'wasm' : 'js';
}

/** Force the JavaScript path ('js') or go back to automatic selection ('auto'). For tests / benchmarks. */
export function setBlurBackend(s: BlurBackendSetting) {
  setting = s;
}

/** Debug details (why WebAssembly isn't used, memory size). */
export function blurBackendInfo(): { backend: BlurBackend; setting: BlurBackendSetting; state: string; reason: string; memoryBytes: number } {
  const backend = blurBackend();
  return { backend, setting, state, reason, memoryBytes: X ? X.memory.buffer.byteLength : 0 };
}

/** Current views of the module's memory (re-created after growth). Do not keep them across wasmAlloc. */
export function wasmHeap() {
  const buf = X!.memory.buffer as ArrayBuffer;
  if (!heapCache || heapCache.buffer !== buf) heapCache = { buffer: buf, u8: new Uint8Array(buf), f32: new Float32Array(buf), f64: new Float64Array(buf), i32: new Int32Array(buf) };
  return heapCache;
}

/** Stack position to hand back to wasmRelease. */
export function wasmMark(): number {
  return top;
}

/**
 * `bytes` of scratch memory (16-byte aligned, contents undefined), or 0 when it can't be had
 * (limit reached / growth refused) — callers then fall back to JavaScript before touching output.
 */
export function wasmAlloc(bytes: number): number {
  if (!X || !(bytes >= 0)) return 0;
  const p = (top + 15) & ~15;
  const end = p + Math.ceil(bytes);
  if (end > MAX_BYTES) return 0;
  const have = X.memory.buffer.byteLength;
  if (end > have) {
    try {
      X.memory.grow(Math.ceil((end - have) / 65536));
    } catch {
      return 0;
    }
  }
  top = end;
  if (end > peak) peak = end;
  return p;
}

/** Tests: memory size above which the instance is recreated, and after how long idle (0 = right after the operation). */
export function setWasmShrinkBytes(n: number, delayMs = 2000) {
  shrinkBytes = n;
  shrinkDelayMs = delayMs;
}

/** Recreate the instance (fresh small memory) if it is idle and oversized. */
function shrinkNow() {
  if (top !== BASE || !mod || !X || X.memory.buffer.byteLength <= shrinkBytes) return;
  try {
    instantiate(mod);
  } catch {
    /* keep the big instance */
  }
}

/**
 * Free everything allocated after `mark`. At the outermost level, oversized memory is handed back
 * once no operation has needed it for shrinkDelayMs (each operation that used more than
 * shrinkBytes restarts the wait; smaller ones don't postpone it).
 */
export function wasmRelease(mark: number) {
  top = mark;
  if (mark !== BASE) return;
  const big = peak > shrinkBytes;
  peak = BASE;
  if (!X || X.memory.buffer.byteLength <= shrinkBytes || (!big && shrinkTimer !== null)) return;
  if (shrinkTimer !== null) clearTimeout(shrinkTimer);
  shrinkTimer = null;
  if (shrinkDelayMs <= 0 || typeof setTimeout !== 'function') return shrinkNow();
  shrinkTimer = setTimeout(() => {
    shrinkTimer = null;
    shrinkNow();
  }, shrinkDelayMs);
  // Node (tests, tools): a pending shrink must not keep the process alive
  (shrinkTimer as { unref?: () => void }).unref?.();
}
